// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thasoegqomyvwhmdbebe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoYXNvZWdxb215dndobWRiZWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NTg4MDksImV4cCI6MjA1NTAzNDgwOX0.37wxwSHOYy01ahPGzmC4gDBcrs26CYttDMQqWyMb6IY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);